import { IMAGE_PATH } from "@/common/constant/imagePath.constant";
import { IChatMessage, IChatroomInfo } from "./detailRoom.interface";

export const MOCK_DATA_INFO_CHATROOM: IChatroomInfo = {
  title: "Layla",
  subtitle: "Active 2m ago",
  image: IMAGE_PATH.onboarding.image_4,
  imageBackground: IMAGE_PATH.onboarding_swipe.image_5,
};

export const MOCK_DATA_CHATTING: IChatMessage[] = [
  {
    sender: "Layla",
    timestamp: "09:41",
    message: "Hello handsome, wyd today?",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
  },
  {
    sender: "Layla",
    timestamp: "09:42",
    message: "Wanna join me?",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
    attachment: {
      type: "image",
      url: IMAGE_PATH.onboarding.image_5,
      isLocked: true,
    },
  },
  {
    sender: "You",
    timestamp: "09:43",
    message: "Here's another one! 🙌",
    isSender: true,
    avatarUrl: IMAGE_PATH.avatars.you,
  },
  {
    sender: "You",
    timestamp: "09:44",
    message: "Last response here 😏",
    isSender: true,
    avatarUrl: IMAGE_PATH.avatars.you,
  },
  {
    sender: "Layla",
    timestamp: "09:45",
    message: "You’re funny 😂",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
  },
  {
    sender: "Layla",
    timestamp: "09:46",
    message: "I bet you can’t keep up with me 😉",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
  },
  {
    sender: "You",
    timestamp: "09:47",
    message: "Try me! 😏",
    isSender: true,
    avatarUrl: IMAGE_PATH.avatars.you,
  },
  {
    sender: "Layla",
    timestamp: "09:48",
    message: "Alright, let’s see!",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
    attachment: {
      type: "image",
      url: IMAGE_PATH.onboarding.image_2,
      isLocked: true,
    },
  },
  {
    sender: "You",
    timestamp: "09:49",
    message: "Not bad! But I’ve got better moves. 💃",
    isSender: true,
    avatarUrl: IMAGE_PATH.avatars.you,
  },
  {
    sender: "Layla",
    timestamp: "09:50",
    message: "Show me then!",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
  },
  {
    sender: "You",
    timestamp: "09:51",
    message: "Challenge accepted. 😎",
    isSender: true,
    avatarUrl: IMAGE_PATH.avatars.you,
  },
  {
    sender: "Layla",
    timestamp: "09:52",
    message: "What’s your plan for tonight?",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
  },
  {
    sender: "You",
    timestamp: "09:53",
    message: "I might just surprise you. 😏",
    isSender: true,
    avatarUrl: IMAGE_PATH.avatars.you,
  },
  {
    sender: "Layla",
    timestamp: "09:54",
    message: "I love surprises! 🌟",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
  },
  {
    sender: "Layla",
    timestamp: "09:55",
    message: "Can you keep a secret though?",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
  },
  {
    sender: "You",
    timestamp: "09:56",
    message: "Always! What’s the secret? 🤔",
    isSender: true,
    avatarUrl: IMAGE_PATH.avatars.you,
  },
  {
    sender: "Layla",
    timestamp: "09:57",
    message: "I think you’re amazing. 😊",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
  },
  {
    sender: "You",
    timestamp: "09:58",
    message: "Wow, that’s sweet. You’re pretty great too! 😇",
    isSender: true,
    avatarUrl: IMAGE_PATH.avatars.you,
  },
  {
    sender: "Layla",
    timestamp: "09:59",
    message: "You just made my day. 🥰",
    isSender: false,
    avatarUrl: IMAGE_PATH.avatars.layla,
  },
  {
    sender: "You",
    timestamp: "10:00",
    message: "Anytime! That’s what I’m here for. ❤️",
    isSender: true,
    avatarUrl: IMAGE_PATH.avatars.you,
  },
];
